CREATE EXTERNAL TABLE IF NOT EXISTS BU_SAC.TA_MEDIO_CTO(
	COD_MEDIO_CONTACTO			INT,			
	DESC_MEDIO_CONTACTO			VARCHAR(48),	
	ORDEN						INT,			
	DATA_DATE_PART				STRING,			
	DATA_TIMESTAMP_PART			BIGINT
)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION '${hiveconf:PATH_AMBIENTE}/chile/desarrollo/002_isban/data/des/landing/sac/TA_MEDIO_CTO'
--TBLPROPERTIES ('PARQUET.COMPRESS'='SNAPPY')
